workspace_root: &workspace_root
  ~/repo

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          key: dependencies-{{ checksum "package-lock.json" }}
          paths:
            - $HOME/.npm
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root

      - run:
          name: Build artifacts
          command: npm run build

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root

      - run:
          name: Run tests
          command: npm test

  deploy-to-hosting:
    <<: *defaults
    steps:
      - attach_workspace:
          at: *workspace_root

      - run:
          name: Deploy to Hosting
          command: sudo apt-get install awscli; aws s3 sync . s3://${S3_BUCKET_NAME}

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - install:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - test:
          requires:
            - install
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - deploy-to-hosting:
          requires:
            - test
          filters:
            branches:
              only: master
